apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-frontend-3
  name: nginx-frontend-3
spec:
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "nginx"
  containers:
  - image: nginx:latest
    name: nginx-frontend-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
