apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod-withnodename
  name: nginx-pod-withnodename
spec:
  containers:
  - image: nginx:latest
    name: nginx-pod-withnodename
    resources: {}
  nodeName: second-kub-cluster-worker2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
