apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx-app-ds
spec:
  selector:
    matchLabels:
      app: nginx-app-ds
  template:
    metadata:
      labels:
        app: nginx-app-ds
    spec:
      containers:
      - name: nginx-ds-container
        image: nginx:latest
        ports:
          - containerPort: 80
